[[redirects]]
  from = "/"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/request"
  to = "/request.html"
  status = 200
